project_name: dfuse-eosio
release:
  github:
    owner: dfuse-io
    name: dfuse-eosio
  draft: true
  name_template: '{{.Tag}}'
before:
  hooks:
    - ./scripts/build.sh -f -p -y
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/dfuseeos
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
  mod_timestamp: '{{ .CommitTimestamp }}'
  binary: dfuseeos
  goos:
    - linux
    - darwin
  goarch:
    - amd64
archives:
- replacements:
    darwin: macOS
    linux: linux
    386: i386
    amd64: x86_64
  files:
  - LICENSE
  - README.md
  - CHANGELOG.md
  - CONTRIBUTING.md
  - DEPENDENCIES.md
  - TROUBLESHOOTING.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - cmd: keybase
    args:
      - sign
      - --infile
      - $artifact
      - --binary
      - --outfile
      - $signature
      - --detached
    signature: ${artifact}.sig
    artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
