// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/statedb/v1/statedb.proto

package pbstatedb

import (
	context "context"
	fmt "fmt"
	v1 "github.com/dfuse-io/pbgo/dfuse/bstream/v1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetABIRequest struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	ToJson               bool     `protobuf:"varint,3,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetABIRequest) Reset()         { *m = GetABIRequest{} }
func (m *GetABIRequest) String() string { return proto.CompactTextString(m) }
func (*GetABIRequest) ProtoMessage()    {}
func (*GetABIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{0}
}

func (m *GetABIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetABIRequest.Unmarshal(m, b)
}
func (m *GetABIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetABIRequest.Marshal(b, m, deterministic)
}
func (m *GetABIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetABIRequest.Merge(m, src)
}
func (m *GetABIRequest) XXX_Size() int {
	return xxx_messageInfo_GetABIRequest.Size(m)
}
func (m *GetABIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetABIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetABIRequest proto.InternalMessageInfo

func (m *GetABIRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *GetABIRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetABIRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

type GetABIResponse struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	RawAbi               []byte   `protobuf:"bytes,2,opt,name=raw_abi,json=rawAbi,proto3" json:"raw_abi,omitempty"`
	JsonAbi              string   `protobuf:"bytes,3,opt,name=json_abi,json=jsonAbi,proto3" json:"json_abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetABIResponse) Reset()         { *m = GetABIResponse{} }
func (m *GetABIResponse) String() string { return proto.CompactTextString(m) }
func (*GetABIResponse) ProtoMessage()    {}
func (*GetABIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{1}
}

func (m *GetABIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetABIResponse.Unmarshal(m, b)
}
func (m *GetABIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetABIResponse.Marshal(b, m, deterministic)
}
func (m *GetABIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetABIResponse.Merge(m, src)
}
func (m *GetABIResponse) XXX_Size() int {
	return xxx_messageInfo_GetABIResponse.Size(m)
}
func (m *GetABIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetABIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetABIResponse proto.InternalMessageInfo

func (m *GetABIResponse) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetABIResponse) GetRawAbi() []byte {
	if m != nil {
		return m.RawAbi
	}
	return nil
}

func (m *GetABIResponse) GetJsonAbi() string {
	if m != nil {
		return m.JsonAbi
	}
	return ""
}

type GetItemOwnersRequest struct {
	ItemId               uint64   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemOwnersRequest) Reset()         { *m = GetItemOwnersRequest{} }
func (m *GetItemOwnersRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemOwnersRequest) ProtoMessage()    {}
func (*GetItemOwnersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{2}
}

func (m *GetItemOwnersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemOwnersRequest.Unmarshal(m, b)
}
func (m *GetItemOwnersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemOwnersRequest.Marshal(b, m, deterministic)
}
func (m *GetItemOwnersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemOwnersRequest.Merge(m, src)
}
func (m *GetItemOwnersRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemOwnersRequest.Size(m)
}
func (m *GetItemOwnersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemOwnersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemOwnersRequest proto.InternalMessageInfo

func (m *GetItemOwnersRequest) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *GetItemOwnersRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

type GetItemTemplateOwnersRequest struct {
	ItemTemplateId       uint64   `protobuf:"varint,1,opt,name=item_template_id,json=itemTemplateId,proto3" json:"item_template_id,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemTemplateOwnersRequest) Reset()         { *m = GetItemTemplateOwnersRequest{} }
func (m *GetItemTemplateOwnersRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemTemplateOwnersRequest) ProtoMessage()    {}
func (*GetItemTemplateOwnersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{3}
}

func (m *GetItemTemplateOwnersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemTemplateOwnersRequest.Unmarshal(m, b)
}
func (m *GetItemTemplateOwnersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemTemplateOwnersRequest.Marshal(b, m, deterministic)
}
func (m *GetItemTemplateOwnersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemTemplateOwnersRequest.Merge(m, src)
}
func (m *GetItemTemplateOwnersRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemTemplateOwnersRequest.Size(m)
}
func (m *GetItemTemplateOwnersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemTemplateOwnersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemTemplateOwnersRequest proto.InternalMessageInfo

func (m *GetItemTemplateOwnersRequest) GetItemTemplateId() uint64 {
	if m != nil {
		return m.ItemTemplateId
	}
	return 0
}

func (m *GetItemTemplateOwnersRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

type GetKeyAccountsRequest struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyAccountsRequest) Reset()         { *m = GetKeyAccountsRequest{} }
func (m *GetKeyAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetKeyAccountsRequest) ProtoMessage()    {}
func (*GetKeyAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{4}
}

func (m *GetKeyAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyAccountsRequest.Unmarshal(m, b)
}
func (m *GetKeyAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetKeyAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyAccountsRequest.Merge(m, src)
}
func (m *GetKeyAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetKeyAccountsRequest.Size(m)
}
func (m *GetKeyAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyAccountsRequest proto.InternalMessageInfo

func (m *GetKeyAccountsRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *GetKeyAccountsRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

type GetKeyAccountsResponse struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Accounts             []string `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyAccountsResponse) Reset()         { *m = GetKeyAccountsResponse{} }
func (m *GetKeyAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeyAccountsResponse) ProtoMessage()    {}
func (*GetKeyAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{5}
}

func (m *GetKeyAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyAccountsResponse.Unmarshal(m, b)
}
func (m *GetKeyAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetKeyAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyAccountsResponse.Merge(m, src)
}
func (m *GetKeyAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeyAccountsResponse.Size(m)
}
func (m *GetKeyAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyAccountsResponse proto.InternalMessageInfo

func (m *GetKeyAccountsResponse) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetKeyAccountsResponse) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetItemOwnersResponse struct {
	BlockNum             uint64       `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Owners               []*ItemOwner `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetItemOwnersResponse) Reset()         { *m = GetItemOwnersResponse{} }
func (m *GetItemOwnersResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemOwnersResponse) ProtoMessage()    {}
func (*GetItemOwnersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{6}
}

func (m *GetItemOwnersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemOwnersResponse.Unmarshal(m, b)
}
func (m *GetItemOwnersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemOwnersResponse.Marshal(b, m, deterministic)
}
func (m *GetItemOwnersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemOwnersResponse.Merge(m, src)
}
func (m *GetItemOwnersResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemOwnersResponse.Size(m)
}
func (m *GetItemOwnersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemOwnersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemOwnersResponse proto.InternalMessageInfo

func (m *GetItemOwnersResponse) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetItemOwnersResponse) GetOwners() []*ItemOwner {
	if m != nil {
		return m.Owners
	}
	return nil
}

type GetItemTemplateOwnersResponse struct {
	BlockNum             uint64       `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Owners               []*ItemOwner `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetItemTemplateOwnersResponse) Reset()         { *m = GetItemTemplateOwnersResponse{} }
func (m *GetItemTemplateOwnersResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemTemplateOwnersResponse) ProtoMessage()    {}
func (*GetItemTemplateOwnersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{7}
}

func (m *GetItemTemplateOwnersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemTemplateOwnersResponse.Unmarshal(m, b)
}
func (m *GetItemTemplateOwnersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemTemplateOwnersResponse.Marshal(b, m, deterministic)
}
func (m *GetItemTemplateOwnersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemTemplateOwnersResponse.Merge(m, src)
}
func (m *GetItemTemplateOwnersResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemTemplateOwnersResponse.Size(m)
}
func (m *GetItemTemplateOwnersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemTemplateOwnersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemTemplateOwnersResponse proto.InternalMessageInfo

func (m *GetItemTemplateOwnersResponse) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetItemTemplateOwnersResponse) GetOwners() []*ItemOwner {
	if m != nil {
		return m.Owners
	}
	return nil
}

type ItemOwner struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	ItemId               uint64   `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemAltId            uint64   `protobuf:"varint,3,opt,name=item_alt_id,json=itemAltId,proto3" json:"item_alt_id,omitempty"`
	ItemTemplateId       uint64   `protobuf:"varint,4,opt,name=item_template_id,json=itemTemplateId,proto3" json:"item_template_id,omitempty"`
	Balance              uint64   `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Owner                string   `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemOwner) Reset()         { *m = ItemOwner{} }
func (m *ItemOwner) String() string { return proto.CompactTextString(m) }
func (*ItemOwner) ProtoMessage()    {}
func (*ItemOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{8}
}

func (m *ItemOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemOwner.Unmarshal(m, b)
}
func (m *ItemOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemOwner.Marshal(b, m, deterministic)
}
func (m *ItemOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemOwner.Merge(m, src)
}
func (m *ItemOwner) XXX_Size() int {
	return xxx_messageInfo_ItemOwner.Size(m)
}
func (m *ItemOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemOwner.DiscardUnknown(m)
}

var xxx_messageInfo_ItemOwner proto.InternalMessageInfo

func (m *ItemOwner) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *ItemOwner) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ItemOwner) GetItemAltId() uint64 {
	if m != nil {
		return m.ItemAltId
	}
	return 0
}

func (m *ItemOwner) GetItemTemplateId() uint64 {
	if m != nil {
		return m.ItemTemplateId
	}
	return 0
}

func (m *ItemOwner) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ItemOwner) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GetPermissionLinksRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionLinksRequest) Reset()         { *m = GetPermissionLinksRequest{} }
func (m *GetPermissionLinksRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermissionLinksRequest) ProtoMessage()    {}
func (*GetPermissionLinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{9}
}

func (m *GetPermissionLinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionLinksRequest.Unmarshal(m, b)
}
func (m *GetPermissionLinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionLinksRequest.Marshal(b, m, deterministic)
}
func (m *GetPermissionLinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionLinksRequest.Merge(m, src)
}
func (m *GetPermissionLinksRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermissionLinksRequest.Size(m)
}
func (m *GetPermissionLinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionLinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionLinksRequest proto.InternalMessageInfo

func (m *GetPermissionLinksRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetPermissionLinksRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetPermissionLinksResponse struct {
	UpToBlock             *v1.BlockRef        `protobuf:"bytes,1,opt,name=up_to_block,json=upToBlock,proto3" json:"up_to_block,omitempty"`
	LastIrreversibleBlock *v1.BlockRef        `protobuf:"bytes,2,opt,name=last_irreversible_block,json=lastIrreversibleBlock,proto3" json:"last_irreversible_block,omitempty"`
	Permissions           []*LinkedPermission `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}            `json:"-"`
	XXX_unrecognized      []byte              `json:"-"`
	XXX_sizecache         int32               `json:"-"`
}

func (m *GetPermissionLinksResponse) Reset()         { *m = GetPermissionLinksResponse{} }
func (m *GetPermissionLinksResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermissionLinksResponse) ProtoMessage()    {}
func (*GetPermissionLinksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{10}
}

func (m *GetPermissionLinksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionLinksResponse.Unmarshal(m, b)
}
func (m *GetPermissionLinksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionLinksResponse.Marshal(b, m, deterministic)
}
func (m *GetPermissionLinksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionLinksResponse.Merge(m, src)
}
func (m *GetPermissionLinksResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermissionLinksResponse.Size(m)
}
func (m *GetPermissionLinksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionLinksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionLinksResponse proto.InternalMessageInfo

func (m *GetPermissionLinksResponse) GetUpToBlock() *v1.BlockRef {
	if m != nil {
		return m.UpToBlock
	}
	return nil
}

func (m *GetPermissionLinksResponse) GetLastIrreversibleBlock() *v1.BlockRef {
	if m != nil {
		return m.LastIrreversibleBlock
	}
	return nil
}

func (m *GetPermissionLinksResponse) GetPermissions() []*LinkedPermission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type LinkedPermission struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	PermissionName       string   `protobuf:"bytes,3,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkedPermission) Reset()         { *m = LinkedPermission{} }
func (m *LinkedPermission) String() string { return proto.CompactTextString(m) }
func (*LinkedPermission) ProtoMessage()    {}
func (*LinkedPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{11}
}

func (m *LinkedPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedPermission.Unmarshal(m, b)
}
func (m *LinkedPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedPermission.Marshal(b, m, deterministic)
}
func (m *LinkedPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedPermission.Merge(m, src)
}
func (m *LinkedPermission) XXX_Size() int {
	return xxx_messageInfo_LinkedPermission.Size(m)
}
func (m *LinkedPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedPermission.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedPermission proto.InternalMessageInfo

func (m *LinkedPermission) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *LinkedPermission) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *LinkedPermission) GetPermissionName() string {
	if m != nil {
		return m.PermissionName
	}
	return ""
}

type GetTableRowRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	KeyType              string   `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ToJson               bool     `protobuf:"varint,3,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	WithBlockNum         bool     `protobuf:"varint,4,opt,name=with_block_num,json=withBlockNum,proto3" json:"with_block_num,omitempty"`
	IrreversibleOnly     bool     `protobuf:"varint,5,opt,name=irreversible_only,json=irreversibleOnly,proto3" json:"irreversible_only,omitempty"`
	Contract             string   `protobuf:"bytes,6,opt,name=contract,proto3" json:"contract,omitempty"`
	Table                string   `protobuf:"bytes,7,opt,name=table,proto3" json:"table,omitempty"`
	Scope                string   `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	PrimaryKey           string   `protobuf:"bytes,9,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTableRowRequest) Reset()         { *m = GetTableRowRequest{} }
func (m *GetTableRowRequest) String() string { return proto.CompactTextString(m) }
func (*GetTableRowRequest) ProtoMessage()    {}
func (*GetTableRowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{12}
}

func (m *GetTableRowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTableRowRequest.Unmarshal(m, b)
}
func (m *GetTableRowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTableRowRequest.Marshal(b, m, deterministic)
}
func (m *GetTableRowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTableRowRequest.Merge(m, src)
}
func (m *GetTableRowRequest) XXX_Size() int {
	return xxx_messageInfo_GetTableRowRequest.Size(m)
}
func (m *GetTableRowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTableRowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTableRowRequest proto.InternalMessageInfo

func (m *GetTableRowRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *GetTableRowRequest) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *GetTableRowRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

func (m *GetTableRowRequest) GetWithBlockNum() bool {
	if m != nil {
		return m.WithBlockNum
	}
	return false
}

func (m *GetTableRowRequest) GetIrreversibleOnly() bool {
	if m != nil {
		return m.IrreversibleOnly
	}
	return false
}

func (m *GetTableRowRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *GetTableRowRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *GetTableRowRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GetTableRowRequest) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

type GetTableRowResponse struct {
	UpToBlock             *v1.BlockRef      `protobuf:"bytes,1,opt,name=up_to_block,json=upToBlock,proto3" json:"up_to_block,omitempty"`
	LastIrreversibleBlock *v1.BlockRef      `protobuf:"bytes,2,opt,name=last_irreversible_block,json=lastIrreversibleBlock,proto3" json:"last_irreversible_block,omitempty"`
	Row                   *TableRowResponse `protobuf:"bytes,3,opt,name=row,proto3" json:"row,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *GetTableRowResponse) Reset()         { *m = GetTableRowResponse{} }
func (m *GetTableRowResponse) String() string { return proto.CompactTextString(m) }
func (*GetTableRowResponse) ProtoMessage()    {}
func (*GetTableRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{13}
}

func (m *GetTableRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTableRowResponse.Unmarshal(m, b)
}
func (m *GetTableRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTableRowResponse.Marshal(b, m, deterministic)
}
func (m *GetTableRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTableRowResponse.Merge(m, src)
}
func (m *GetTableRowResponse) XXX_Size() int {
	return xxx_messageInfo_GetTableRowResponse.Size(m)
}
func (m *GetTableRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTableRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTableRowResponse proto.InternalMessageInfo

func (m *GetTableRowResponse) GetUpToBlock() *v1.BlockRef {
	if m != nil {
		return m.UpToBlock
	}
	return nil
}

func (m *GetTableRowResponse) GetLastIrreversibleBlock() *v1.BlockRef {
	if m != nil {
		return m.LastIrreversibleBlock
	}
	return nil
}

func (m *GetTableRowResponse) GetRow() *TableRowResponse {
	if m != nil {
		return m.Row
	}
	return nil
}

type StreamTableRowsRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	KeyType              string   `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ToJson               bool     `protobuf:"varint,3,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	WithBlockNum         bool     `protobuf:"varint,4,opt,name=with_block_num,json=withBlockNum,proto3" json:"with_block_num,omitempty"`
	IrreversibleOnly     bool     `protobuf:"varint,5,opt,name=irreversible_only,json=irreversibleOnly,proto3" json:"irreversible_only,omitempty"`
	Contract             string   `protobuf:"bytes,6,opt,name=contract,proto3" json:"contract,omitempty"`
	Table                string   `protobuf:"bytes,7,opt,name=table,proto3" json:"table,omitempty"`
	Scope                string   `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamTableRowsRequest) Reset()         { *m = StreamTableRowsRequest{} }
func (m *StreamTableRowsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamTableRowsRequest) ProtoMessage()    {}
func (*StreamTableRowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{14}
}

func (m *StreamTableRowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTableRowsRequest.Unmarshal(m, b)
}
func (m *StreamTableRowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTableRowsRequest.Marshal(b, m, deterministic)
}
func (m *StreamTableRowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTableRowsRequest.Merge(m, src)
}
func (m *StreamTableRowsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamTableRowsRequest.Size(m)
}
func (m *StreamTableRowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTableRowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTableRowsRequest proto.InternalMessageInfo

func (m *StreamTableRowsRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *StreamTableRowsRequest) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *StreamTableRowsRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

func (m *StreamTableRowsRequest) GetWithBlockNum() bool {
	if m != nil {
		return m.WithBlockNum
	}
	return false
}

func (m *StreamTableRowsRequest) GetIrreversibleOnly() bool {
	if m != nil {
		return m.IrreversibleOnly
	}
	return false
}

func (m *StreamTableRowsRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *StreamTableRowsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *StreamTableRowsRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type TableRowResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Json                 string   `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	Payer                string   `protobuf:"bytes,4,opt,name=payer,proto3" json:"payer,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableRowResponse) Reset()         { *m = TableRowResponse{} }
func (m *TableRowResponse) String() string { return proto.CompactTextString(m) }
func (*TableRowResponse) ProtoMessage()    {}
func (*TableRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{15}
}

func (m *TableRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRowResponse.Unmarshal(m, b)
}
func (m *TableRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRowResponse.Marshal(b, m, deterministic)
}
func (m *TableRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRowResponse.Merge(m, src)
}
func (m *TableRowResponse) XXX_Size() int {
	return xxx_messageInfo_TableRowResponse.Size(m)
}
func (m *TableRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TableRowResponse proto.InternalMessageInfo

func (m *TableRowResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TableRowResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TableRowResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *TableRowResponse) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *TableRowResponse) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type StreamTableScopesRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Contract             string   `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamTableScopesRequest) Reset()         { *m = StreamTableScopesRequest{} }
func (m *StreamTableScopesRequest) String() string { return proto.CompactTextString(m) }
func (*StreamTableScopesRequest) ProtoMessage()    {}
func (*StreamTableScopesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{16}
}

func (m *StreamTableScopesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTableScopesRequest.Unmarshal(m, b)
}
func (m *StreamTableScopesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTableScopesRequest.Marshal(b, m, deterministic)
}
func (m *StreamTableScopesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTableScopesRequest.Merge(m, src)
}
func (m *StreamTableScopesRequest) XXX_Size() int {
	return xxx_messageInfo_StreamTableScopesRequest.Size(m)
}
func (m *StreamTableScopesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTableScopesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTableScopesRequest proto.InternalMessageInfo

func (m *StreamTableScopesRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *StreamTableScopesRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *StreamTableScopesRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type TableScopeResponse struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableScopeResponse) Reset()         { *m = TableScopeResponse{} }
func (m *TableScopeResponse) String() string { return proto.CompactTextString(m) }
func (*TableScopeResponse) ProtoMessage()    {}
func (*TableScopeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{17}
}

func (m *TableScopeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableScopeResponse.Unmarshal(m, b)
}
func (m *TableScopeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableScopeResponse.Marshal(b, m, deterministic)
}
func (m *TableScopeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableScopeResponse.Merge(m, src)
}
func (m *TableScopeResponse) XXX_Size() int {
	return xxx_messageInfo_TableScopeResponse.Size(m)
}
func (m *TableScopeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TableScopeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TableScopeResponse proto.InternalMessageInfo

func (m *TableScopeResponse) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *TableScopeResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type StreamMultiScopesTableRowsRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Contract             string   `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	KeyType              string   `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ToJson               bool     `protobuf:"varint,5,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	WithBlockNum         bool     `protobuf:"varint,6,opt,name=with_block_num,json=withBlockNum,proto3" json:"with_block_num,omitempty"`
	IrreversibleOnly     bool     `protobuf:"varint,7,opt,name=irreversible_only,json=irreversibleOnly,proto3" json:"irreversible_only,omitempty"`
	Scopes               []string `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMultiScopesTableRowsRequest) Reset()         { *m = StreamMultiScopesTableRowsRequest{} }
func (m *StreamMultiScopesTableRowsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamMultiScopesTableRowsRequest) ProtoMessage()    {}
func (*StreamMultiScopesTableRowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{18}
}

func (m *StreamMultiScopesTableRowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMultiScopesTableRowsRequest.Unmarshal(m, b)
}
func (m *StreamMultiScopesTableRowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMultiScopesTableRowsRequest.Marshal(b, m, deterministic)
}
func (m *StreamMultiScopesTableRowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMultiScopesTableRowsRequest.Merge(m, src)
}
func (m *StreamMultiScopesTableRowsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamMultiScopesTableRowsRequest.Size(m)
}
func (m *StreamMultiScopesTableRowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMultiScopesTableRowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMultiScopesTableRowsRequest proto.InternalMessageInfo

func (m *StreamMultiScopesTableRowsRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *StreamMultiScopesTableRowsRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *StreamMultiScopesTableRowsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *StreamMultiScopesTableRowsRequest) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *StreamMultiScopesTableRowsRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

func (m *StreamMultiScopesTableRowsRequest) GetWithBlockNum() bool {
	if m != nil {
		return m.WithBlockNum
	}
	return false
}

func (m *StreamMultiScopesTableRowsRequest) GetIrreversibleOnly() bool {
	if m != nil {
		return m.IrreversibleOnly
	}
	return false
}

func (m *StreamMultiScopesTableRowsRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type StreamMultiContractsTableRowsRequest struct {
	BlockNum             uint64   `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Table                string   `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	KeyType              string   `protobuf:"bytes,4,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	ToJson               bool     `protobuf:"varint,5,opt,name=to_json,json=toJson,proto3" json:"to_json,omitempty"`
	WithBlockNum         bool     `protobuf:"varint,6,opt,name=with_block_num,json=withBlockNum,proto3" json:"with_block_num,omitempty"`
	IrreversibleOnly     bool     `protobuf:"varint,7,opt,name=irreversible_only,json=irreversibleOnly,proto3" json:"irreversible_only,omitempty"`
	Contracts            []string `protobuf:"bytes,8,rep,name=contracts,proto3" json:"contracts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMultiContractsTableRowsRequest) Reset()         { *m = StreamMultiContractsTableRowsRequest{} }
func (m *StreamMultiContractsTableRowsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamMultiContractsTableRowsRequest) ProtoMessage()    {}
func (*StreamMultiContractsTableRowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{19}
}

func (m *StreamMultiContractsTableRowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMultiContractsTableRowsRequest.Unmarshal(m, b)
}
func (m *StreamMultiContractsTableRowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMultiContractsTableRowsRequest.Marshal(b, m, deterministic)
}
func (m *StreamMultiContractsTableRowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMultiContractsTableRowsRequest.Merge(m, src)
}
func (m *StreamMultiContractsTableRowsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamMultiContractsTableRowsRequest.Size(m)
}
func (m *StreamMultiContractsTableRowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMultiContractsTableRowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMultiContractsTableRowsRequest proto.InternalMessageInfo

func (m *StreamMultiContractsTableRowsRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *StreamMultiContractsTableRowsRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *StreamMultiContractsTableRowsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *StreamMultiContractsTableRowsRequest) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *StreamMultiContractsTableRowsRequest) GetToJson() bool {
	if m != nil {
		return m.ToJson
	}
	return false
}

func (m *StreamMultiContractsTableRowsRequest) GetWithBlockNum() bool {
	if m != nil {
		return m.WithBlockNum
	}
	return false
}

func (m *StreamMultiContractsTableRowsRequest) GetIrreversibleOnly() bool {
	if m != nil {
		return m.IrreversibleOnly
	}
	return false
}

func (m *StreamMultiContractsTableRowsRequest) GetContracts() []string {
	if m != nil {
		return m.Contracts
	}
	return nil
}

type TableRowsScopeResponse struct {
	Scope                string              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Rows                 []*TableRowResponse `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TableRowsScopeResponse) Reset()         { *m = TableRowsScopeResponse{} }
func (m *TableRowsScopeResponse) String() string { return proto.CompactTextString(m) }
func (*TableRowsScopeResponse) ProtoMessage()    {}
func (*TableRowsScopeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{20}
}

func (m *TableRowsScopeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRowsScopeResponse.Unmarshal(m, b)
}
func (m *TableRowsScopeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRowsScopeResponse.Marshal(b, m, deterministic)
}
func (m *TableRowsScopeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRowsScopeResponse.Merge(m, src)
}
func (m *TableRowsScopeResponse) XXX_Size() int {
	return xxx_messageInfo_TableRowsScopeResponse.Size(m)
}
func (m *TableRowsScopeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRowsScopeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TableRowsScopeResponse proto.InternalMessageInfo

func (m *TableRowsScopeResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *TableRowsScopeResponse) GetRows() []*TableRowResponse {
	if m != nil {
		return m.Rows
	}
	return nil
}

type TableRowsContractResponse struct {
	Contract             string              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Rows                 []*TableRowResponse `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TableRowsContractResponse) Reset()         { *m = TableRowsContractResponse{} }
func (m *TableRowsContractResponse) String() string { return proto.CompactTextString(m) }
func (*TableRowsContractResponse) ProtoMessage()    {}
func (*TableRowsContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eba888d47f0653d, []int{21}
}

func (m *TableRowsContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRowsContractResponse.Unmarshal(m, b)
}
func (m *TableRowsContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRowsContractResponse.Marshal(b, m, deterministic)
}
func (m *TableRowsContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRowsContractResponse.Merge(m, src)
}
func (m *TableRowsContractResponse) XXX_Size() int {
	return xxx_messageInfo_TableRowsContractResponse.Size(m)
}
func (m *TableRowsContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRowsContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TableRowsContractResponse proto.InternalMessageInfo

func (m *TableRowsContractResponse) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *TableRowsContractResponse) GetRows() []*TableRowResponse {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*GetABIRequest)(nil), "dfuse.eosio.statedb.v1.GetABIRequest")
	proto.RegisterType((*GetABIResponse)(nil), "dfuse.eosio.statedb.v1.GetABIResponse")
	proto.RegisterType((*GetItemOwnersRequest)(nil), "dfuse.eosio.statedb.v1.GetItemOwnersRequest")
	proto.RegisterType((*GetItemTemplateOwnersRequest)(nil), "dfuse.eosio.statedb.v1.GetItemTemplateOwnersRequest")
	proto.RegisterType((*GetKeyAccountsRequest)(nil), "dfuse.eosio.statedb.v1.GetKeyAccountsRequest")
	proto.RegisterType((*GetKeyAccountsResponse)(nil), "dfuse.eosio.statedb.v1.GetKeyAccountsResponse")
	proto.RegisterType((*GetItemOwnersResponse)(nil), "dfuse.eosio.statedb.v1.GetItemOwnersResponse")
	proto.RegisterType((*GetItemTemplateOwnersResponse)(nil), "dfuse.eosio.statedb.v1.GetItemTemplateOwnersResponse")
	proto.RegisterType((*ItemOwner)(nil), "dfuse.eosio.statedb.v1.ItemOwner")
	proto.RegisterType((*GetPermissionLinksRequest)(nil), "dfuse.eosio.statedb.v1.GetPermissionLinksRequest")
	proto.RegisterType((*GetPermissionLinksResponse)(nil), "dfuse.eosio.statedb.v1.GetPermissionLinksResponse")
	proto.RegisterType((*LinkedPermission)(nil), "dfuse.eosio.statedb.v1.LinkedPermission")
	proto.RegisterType((*GetTableRowRequest)(nil), "dfuse.eosio.statedb.v1.GetTableRowRequest")
	proto.RegisterType((*GetTableRowResponse)(nil), "dfuse.eosio.statedb.v1.GetTableRowResponse")
	proto.RegisterType((*StreamTableRowsRequest)(nil), "dfuse.eosio.statedb.v1.StreamTableRowsRequest")
	proto.RegisterType((*TableRowResponse)(nil), "dfuse.eosio.statedb.v1.TableRowResponse")
	proto.RegisterType((*StreamTableScopesRequest)(nil), "dfuse.eosio.statedb.v1.StreamTableScopesRequest")
	proto.RegisterType((*TableScopeResponse)(nil), "dfuse.eosio.statedb.v1.TableScopeResponse")
	proto.RegisterType((*StreamMultiScopesTableRowsRequest)(nil), "dfuse.eosio.statedb.v1.StreamMultiScopesTableRowsRequest")
	proto.RegisterType((*StreamMultiContractsTableRowsRequest)(nil), "dfuse.eosio.statedb.v1.StreamMultiContractsTableRowsRequest")
	proto.RegisterType((*TableRowsScopeResponse)(nil), "dfuse.eosio.statedb.v1.TableRowsScopeResponse")
	proto.RegisterType((*TableRowsContractResponse)(nil), "dfuse.eosio.statedb.v1.TableRowsContractResponse")
}

func init() {
	proto.RegisterFile("dfuse/eosio/statedb/v1/statedb.proto", fileDescriptor_7eba888d47f0653d)
}

var fileDescriptor_7eba888d47f0653d = []byte{
	// 1178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0x96, 0x93, 0x34, 0x7f, 0x4e, 0xfa, 0xeb, 0x76, 0xe7, 0xd7, 0x4d, 0x5d, 0xb3, 0x5d, 0x5a,
	0xab, 0x40, 0xb5, 0x2b, 0x92, 0xb6, 0x5c, 0xed, 0xb2, 0x37, 0x2d, 0x42, 0x51, 0xb7, 0xcb, 0x2e,
	0xb8, 0x95, 0x90, 0xb8, 0x89, 0xc6, 0xc9, 0x74, 0x6b, 0x6a, 0x7b, 0x8c, 0x67, 0xdc, 0x60, 0xb8,
	0x85, 0x0b, 0x2e, 0x41, 0xbc, 0x00, 0xcf, 0xb1, 0x4f, 0xc3, 0x5b, 0x70, 0x89, 0x3c, 0x1e, 0x3b,
	0x76, 0x1a, 0x3b, 0xae, 0x10, 0xd2, 0x4a, 0xdc, 0xcd, 0x99, 0x99, 0xf3, 0x9d, 0x39, 0xdf, 0xf9,
	0x72, 0x66, 0x1c, 0xd8, 0x9b, 0x5c, 0x06, 0x8c, 0x0c, 0x08, 0x65, 0x16, 0x1d, 0x30, 0x8e, 0x39,
	0x99, 0x98, 0x83, 0x9b, 0xc3, 0x64, 0xd8, 0xf7, 0x7c, 0xca, 0x29, 0xea, 0x89, 0x5d, 0x7d, 0xb1,
	0xab, 0x9f, 0x2c, 0xdd, 0x1c, 0x6a, 0x8f, 0x62, 0x6f, 0x93, 0x71, 0x9f, 0x60, 0x27, 0xf2, 0x93,
	0xc3, 0xd8, 0x4f, 0xc7, 0xf0, 0xbf, 0x21, 0xe1, 0xc7, 0x27, 0xa7, 0x06, 0xf9, 0x2e, 0x20, 0x8c,
	0x23, 0x0d, 0xda, 0x63, 0xea, 0x72, 0x1f, 0x8f, 0xb9, 0xaa, 0xec, 0x28, 0xfb, 0x1d, 0x23, 0xb5,
	0xd1, 0x7b, 0xd0, 0x31, 0x6d, 0x3a, 0xbe, 0x1e, 0xb9, 0x81, 0xa3, 0xd6, 0x76, 0x94, 0xfd, 0x86,
	0xd1, 0x16, 0x13, 0xaf, 0x02, 0x07, 0x6d, 0x42, 0x8b, 0xd3, 0xd1, 0xb7, 0x8c, 0xba, 0x6a, 0x7d,
	0x47, 0xd9, 0x6f, 0x1b, 0x4d, 0x4e, 0x5f, 0x30, 0xea, 0xea, 0x18, 0xd6, 0x92, 0x10, 0xcc, 0xa3,
	0x2e, 0x23, 0x79, 0x1c, 0xe5, 0x36, 0x8e, 0x8f, 0xa7, 0x23, 0x6c, 0x5a, 0x22, 0xc4, 0xaa, 0xd1,
	0xf4, 0xf1, 0xf4, 0xd8, 0xb4, 0xd0, 0x16, 0xb4, 0x23, 0x74, 0xb1, 0x52, 0x17, 0x27, 0x6b, 0x45,
	0xf6, 0xb1, 0x69, 0xe9, 0x2f, 0x61, 0x63, 0x48, 0xf8, 0x29, 0x27, 0xce, 0xeb, 0xa9, 0x4b, 0x7c,
	0x96, 0x24, 0xb3, 0x09, 0x2d, 0x8b, 0x13, 0x67, 0x64, 0x4d, 0x64, 0x98, 0x66, 0x64, 0x9e, 0x4e,
	0x4a, 0x33, 0xd1, 0x09, 0x3c, 0x94, 0x68, 0x17, 0xc4, 0xf1, 0x6c, 0xcc, 0x49, 0x1e, 0x75, 0x1f,
	0xd6, 0x05, 0x2a, 0x97, 0xab, 0x33, 0xf8, 0x35, 0x2b, 0xe3, 0xb4, 0x2c, 0xcc, 0x39, 0x3c, 0x18,
	0x12, 0x7e, 0x46, 0xc2, 0xe3, 0xf1, 0x98, 0x06, 0x2e, 0x4f, 0xf1, 0xb7, 0x01, 0xbc, 0xc0, 0xb4,
	0xad, 0xf1, 0xe8, 0x9a, 0x84, 0xb2, 0x08, 0x9d, 0x78, 0xe6, 0x8c, 0x84, 0xe5, 0xa0, 0x5f, 0x41,
	0x6f, 0x1e, 0xb4, 0x0a, 0xe9, 0x1a, 0xb4, 0xb1, 0x74, 0x50, 0x6b, 0x3b, 0xf5, 0xa8, 0xea, 0x89,
	0xad, 0x53, 0x71, 0xce, 0x2c, 0xb9, 0x55, 0x10, 0x9f, 0x42, 0x93, 0x8a, 0xed, 0x02, 0xaf, 0x7b,
	0xb4, 0xdb, 0x5f, 0xac, 0xd0, 0x7e, 0x0a, 0x6c, 0x48, 0x07, 0x7d, 0x0a, 0xdb, 0x05, 0xfc, 0xff,
	0xcb, 0x81, 0xdf, 0x2a, 0xd0, 0x49, 0x67, 0x97, 0xaa, 0x34, 0x51, 0x56, 0x2d, 0xa7, 0xac, 0x47,
	0xd0, 0x15, 0x0b, 0xd8, 0xe6, 0xd1, 0x62, 0x5d, 0x2c, 0x76, 0xa2, 0xa9, 0x63, 0x9b, 0x9f, 0x4e,
	0x16, 0x8a, 0xa7, 0xb1, 0x50, 0x3c, 0x2a, 0xb4, 0x4c, 0x6c, 0x63, 0x77, 0x4c, 0xd4, 0x15, 0xb1,
	0x21, 0x31, 0xd1, 0x06, 0xac, 0x88, 0x13, 0xab, 0x4d, 0xa1, 0x8d, 0xd8, 0xd0, 0x0d, 0xd8, 0x1a,
	0x12, 0xfe, 0x25, 0xf1, 0x1d, 0x8b, 0x31, 0x8b, 0xba, 0x2f, 0x2d, 0xf7, 0x3a, 0xd5, 0x54, 0x69,
	0x32, 0x2a, 0xb4, 0x64, 0xb5, 0x45, 0x32, 0x1d, 0x23, 0x31, 0xf5, 0xbf, 0x14, 0xd0, 0x16, 0x81,
	0xca, 0x42, 0x3c, 0x83, 0x6e, 0xe0, 0x8d, 0x38, 0x1d, 0x09, 0x28, 0x81, 0xdb, 0x3d, 0xd2, 0x24,
	0xe1, 0x49, 0xa3, 0xb9, 0x39, 0xec, 0x9f, 0x44, 0xcb, 0x06, 0xb9, 0x34, 0x3a, 0x81, 0x77, 0x41,
	0x85, 0x85, 0x0c, 0xd8, 0xb4, 0x31, 0xe3, 0x23, 0xcb, 0xf7, 0xc9, 0x0d, 0xf1, 0x99, 0x65, 0xda,
	0x44, 0xe2, 0xd4, 0x96, 0xe2, 0x3c, 0x88, 0x5c, 0x4f, 0x33, 0x9e, 0x31, 0xe6, 0x0b, 0xe8, 0x7a,
	0xe9, 0x51, 0x99, 0x5a, 0x17, 0x02, 0xd8, 0x2f, 0x12, 0x40, 0x94, 0x0b, 0x99, 0xcc, 0x72, 0x33,
	0xb2, 0xce, 0x3a, 0x85, 0xf5, 0xf9, 0x0d, 0xa5, 0xcd, 0xb1, 0x07, 0x4d, 0x3c, 0xe6, 0x16, 0x75,
	0x25, 0x87, 0xd2, 0x42, 0x1f, 0xc1, 0xbd, 0x19, 0xec, 0xc8, 0xc5, 0x0e, 0x91, 0xdd, 0x6b, 0x6d,
	0x36, 0xfd, 0x0a, 0x3b, 0x44, 0xff, 0xa3, 0x06, 0x68, 0x48, 0xf8, 0x05, 0x36, 0x6d, 0x62, 0xd0,
	0x69, 0xa5, 0xca, 0x6d, 0x41, 0xfb, 0x9a, 0x84, 0x23, 0x1e, 0x7a, 0x24, 0x29, 0xdd, 0x35, 0x09,
	0x2f, 0x42, 0x8f, 0x14, 0xf6, 0x63, 0xb4, 0x07, 0x6b, 0x53, 0x8b, 0x5f, 0x8d, 0x66, 0xa8, 0x0d,
	0xb1, 0xbe, 0x1a, 0xcd, 0x9e, 0x24, 0xc8, 0x4f, 0xe0, 0x7e, 0xae, 0x32, 0xd4, 0xb5, 0x43, 0xa1,
	0xc3, 0xb6, 0xb1, 0x9e, 0x5d, 0x78, 0xed, 0xda, 0x61, 0x8e, 0x97, 0xe6, 0x1c, 0x2f, 0x1b, 0xb0,
	0xc2, 0xa3, 0x94, 0xd4, 0x56, 0x2c, 0x56, 0x61, 0x44, 0xb3, 0x6c, 0x4c, 0x3d, 0xa2, 0xb6, 0xe3,
	0x59, 0x61, 0xa0, 0xf7, 0xa1, 0xeb, 0xf9, 0x96, 0x83, 0xfd, 0x50, 0xb4, 0xbe, 0x8e, 0x58, 0x03,
	0x39, 0x75, 0x46, 0x42, 0xfd, 0x4f, 0x05, 0xfe, 0x9f, 0xe3, 0xe8, 0x1d, 0x15, 0xe2, 0x33, 0xa8,
	0xfb, 0x74, 0x2a, 0x88, 0x2f, 0x11, 0xe0, 0x7c, 0x1a, 0x46, 0xe4, 0xa4, 0xff, 0x54, 0x83, 0xde,
	0xb9, 0x88, 0x94, 0xac, 0xb3, 0xff, 0xa0, 0x16, 0xf4, 0x9f, 0x15, 0x58, 0xbf, 0x55, 0xe7, 0x75,
	0xa8, 0xcf, 0xee, 0xc4, 0x68, 0x88, 0x10, 0x34, 0x26, 0x98, 0x63, 0xf9, 0x56, 0x10, 0xe3, 0x68,
	0x2e, 0xcd, 0xb5, 0x63, 0x88, 0x71, 0x14, 0xc4, 0xc3, 0x21, 0xf1, 0x45, 0x82, 0x1d, 0x23, 0x36,
	0xd0, 0x2e, 0xac, 0xa6, 0xa9, 0x9b, 0xc4, 0x97, 0x8d, 0xb6, 0x9b, 0x70, 0x6a, 0x12, 0x5f, 0xb7,
	0x40, 0xcd, 0x54, 0xe3, 0x3c, 0x3a, 0x5b, 0xb5, 0x7a, 0x64, 0x89, 0xa8, 0x15, 0x11, 0x51, 0xcf,
	0x10, 0xa1, 0x0f, 0x01, 0xcd, 0x82, 0x54, 0xbb, 0xed, 0x52, 0xee, 0x6a, 0x59, 0xee, 0x7e, 0xad,
	0xc1, 0x6e, 0x7c, 0xe8, 0x2f, 0x02, 0x9b, 0x5b, 0xf1, 0xa1, 0xef, 0xa6, 0xa6, 0x3b, 0x9f, 0x3e,
	0xa7, 0xbf, 0x46, 0xa1, 0xfe, 0x56, 0x96, 0xe8, 0xaf, 0x59, 0x55, 0x7f, 0xad, 0x02, 0xfd, 0xf5,
	0xa0, 0x29, 0x48, 0x60, 0x6a, 0x5b, 0x3c, 0x64, 0xa4, 0xa5, 0xff, 0x5e, 0x83, 0xbd, 0x0c, 0x27,
	0x9f, 0xc9, 0x64, 0xee, 0x48, 0xcb, 0x42, 0xbe, 0xdf, 0x6d, 0x42, 0x1e, 0x42, 0x27, 0xa9, 0x5c,
	0xc2, 0xc9, 0x6c, 0x42, 0xb7, 0xa1, 0x97, 0x32, 0x90, 0xd7, 0x5d, 0x9a, 0xaa, 0x92, 0x4d, 0xf5,
	0x39, 0x34, 0x7c, 0x3a, 0x65, 0x6a, 0xa3, 0xfc, 0x6e, 0xbd, 0xd5, 0xda, 0x84, 0x97, 0x1e, 0xc0,
	0x56, 0x1a, 0x2d, 0xa9, 0x40, 0x1a, 0xb0, 0xec, 0x76, 0xfd, 0x47, 0x61, 0x8f, 0xde, 0xb6, 0x60,
	0xe5, 0x3c, 0xda, 0x85, 0xbe, 0x86, 0x66, 0xfc, 0x31, 0x82, 0x3e, 0x28, 0xc2, 0xc8, 0x7d, 0x0f,
	0x69, 0x1f, 0x2e, 0xdb, 0x26, 0x0f, 0x4f, 0xc5, 0x57, 0x4e, 0xe6, 0xe1, 0x8d, 0x3e, 0x2e, 0xf1,
	0xbc, 0xfd, 0xea, 0xd7, 0xfa, 0x55, 0xb7, 0xcb, 0x80, 0x3f, 0x8a, 0xd7, 0xc2, 0xdc, 0xcb, 0x0c,
	0x1d, 0x96, 0xa0, 0x2c, 0x7e, 0x1a, 0x6a, 0x47, 0x77, 0x71, 0x91, 0xc1, 0x2f, 0xa1, 0x9b, 0xb9,
	0x86, 0xd1, 0xe3, 0x12, 0x88, 0xb9, 0xf7, 0x8c, 0xf6, 0xa4, 0xd2, 0x5e, 0x19, 0xc7, 0x81, 0x7b,
	0x73, 0x57, 0x21, 0x2a, 0xe4, 0x69, 0xf1, 0x9d, 0xa9, 0x55, 0xd6, 0xca, 0x81, 0x82, 0x18, 0xdc,
	0xbf, 0xd5, 0xeb, 0xd1, 0x41, 0x85, 0x80, 0xb9, 0x6b, 0x41, 0x7b, 0x5c, 0x1a, 0x32, 0xf7, 0x2b,
	0x3b, 0x50, 0xd0, 0x2f, 0x0a, 0x68, 0xc5, 0xcd, 0x1a, 0x3d, 0x2d, 0x0f, 0x5f, 0xd2, 0xe0, 0x8b,
	0x25, 0xb5, 0xf8, 0x17, 0x7f, 0xa0, 0xa0, 0xdf, 0x14, 0xd8, 0x2e, 0x6d, 0x92, 0xe8, 0x79, 0x85,
	0xe3, 0x14, 0xf6, 0x56, 0xed, 0x70, 0xe9, 0x89, 0xe6, 0xbb, 0xc2, 0x81, 0x72, 0x32, 0xfc, 0xe6,
	0xf3, 0x37, 0x16, 0xbf, 0x0a, 0xcc, 0xfe, 0x98, 0x3a, 0x83, 0x1f, 0xae, 0xa8, 0xfb, 0x86, 0x5d,
	0x05, 0x53, 0xe2, 0x0e, 0xae, 0x2c, 0xc6, 0xa9, 0x1f, 0x92, 0xef, 0xbd, 0x81, 0x67, 0x0e, 0x16,
	0xff, 0x51, 0xf2, 0xa9, 0x67, 0x4a, 0xc3, 0x6c, 0x8a, 0xff, 0x3c, 0x3e, 0xf9, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0x8c, 0x8c, 0xfc, 0x53, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StateClient is the client API for State service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateClient interface {
	// Replaces /v0/state/abi
	GetABI(ctx context.Context, in *GetABIRequest, opts ...grpc.CallOption) (*GetABIResponse, error)
	// Replaces /v0/state/key_accounts
	GetKeyAccounts(ctx context.Context, in *GetKeyAccountsRequest, opts ...grpc.CallOption) (*GetKeyAccountsResponse, error)
	// Replaces /v0/state/permission_links
	GetPermissionLinks(ctx context.Context, in *GetPermissionLinksRequest, opts ...grpc.CallOption) (*GetPermissionLinksResponse, error)
	// Replaces /v0/state/table/row
	GetTableRow(ctx context.Context, in *GetTableRowRequest, opts ...grpc.CallOption) (*GetTableRowResponse, error)
	// Replaces /v0/state/table
	StreamTableRows(ctx context.Context, in *StreamTableRowsRequest, opts ...grpc.CallOption) (State_StreamTableRowsClient, error)
	// Replaces /v0/state/table_scopes
	StreamTableScopes(ctx context.Context, in *StreamTableScopesRequest, opts ...grpc.CallOption) (State_StreamTableScopesClient, error)
	// Replaces /v0/state/tables/scopes
	StreamMultiScopesTableRows(ctx context.Context, in *StreamMultiScopesTableRowsRequest, opts ...grpc.CallOption) (State_StreamMultiScopesTableRowsClient, error)
	// Replaces /v0/state/tables/accounts
	StreamMultiContractsTableRows(ctx context.Context, in *StreamMultiContractsTableRowsRequest, opts ...grpc.CallOption) (State_StreamMultiContractsTableRowsClient, error)
}

type stateClient struct {
	cc grpc.ClientConnInterface
}

func NewStateClient(cc grpc.ClientConnInterface) StateClient {
	return &stateClient{cc}
}

func (c *stateClient) GetABI(ctx context.Context, in *GetABIRequest, opts ...grpc.CallOption) (*GetABIResponse, error) {
	out := new(GetABIResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.statedb.v1.State/GetABI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetKeyAccounts(ctx context.Context, in *GetKeyAccountsRequest, opts ...grpc.CallOption) (*GetKeyAccountsResponse, error) {
	out := new(GetKeyAccountsResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.statedb.v1.State/GetKeyAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetPermissionLinks(ctx context.Context, in *GetPermissionLinksRequest, opts ...grpc.CallOption) (*GetPermissionLinksResponse, error) {
	out := new(GetPermissionLinksResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.statedb.v1.State/GetPermissionLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) GetTableRow(ctx context.Context, in *GetTableRowRequest, opts ...grpc.CallOption) (*GetTableRowResponse, error) {
	out := new(GetTableRowResponse)
	err := c.cc.Invoke(ctx, "/dfuse.eosio.statedb.v1.State/GetTableRow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) StreamTableRows(ctx context.Context, in *StreamTableRowsRequest, opts ...grpc.CallOption) (State_StreamTableRowsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_State_serviceDesc.Streams[0], "/dfuse.eosio.statedb.v1.State/StreamTableRows", opts...)
	if err != nil {
		return nil, err
	}
	x := &stateStreamTableRowsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type State_StreamTableRowsClient interface {
	Recv() (*TableRowResponse, error)
	grpc.ClientStream
}

type stateStreamTableRowsClient struct {
	grpc.ClientStream
}

func (x *stateStreamTableRowsClient) Recv() (*TableRowResponse, error) {
	m := new(TableRowResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stateClient) StreamTableScopes(ctx context.Context, in *StreamTableScopesRequest, opts ...grpc.CallOption) (State_StreamTableScopesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_State_serviceDesc.Streams[1], "/dfuse.eosio.statedb.v1.State/StreamTableScopes", opts...)
	if err != nil {
		return nil, err
	}
	x := &stateStreamTableScopesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type State_StreamTableScopesClient interface {
	Recv() (*TableScopeResponse, error)
	grpc.ClientStream
}

type stateStreamTableScopesClient struct {
	grpc.ClientStream
}

func (x *stateStreamTableScopesClient) Recv() (*TableScopeResponse, error) {
	m := new(TableScopeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stateClient) StreamMultiScopesTableRows(ctx context.Context, in *StreamMultiScopesTableRowsRequest, opts ...grpc.CallOption) (State_StreamMultiScopesTableRowsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_State_serviceDesc.Streams[2], "/dfuse.eosio.statedb.v1.State/StreamMultiScopesTableRows", opts...)
	if err != nil {
		return nil, err
	}
	x := &stateStreamMultiScopesTableRowsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type State_StreamMultiScopesTableRowsClient interface {
	Recv() (*TableRowsScopeResponse, error)
	grpc.ClientStream
}

type stateStreamMultiScopesTableRowsClient struct {
	grpc.ClientStream
}

func (x *stateStreamMultiScopesTableRowsClient) Recv() (*TableRowsScopeResponse, error) {
	m := new(TableRowsScopeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stateClient) StreamMultiContractsTableRows(ctx context.Context, in *StreamMultiContractsTableRowsRequest, opts ...grpc.CallOption) (State_StreamMultiContractsTableRowsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_State_serviceDesc.Streams[3], "/dfuse.eosio.statedb.v1.State/StreamMultiContractsTableRows", opts...)
	if err != nil {
		return nil, err
	}
	x := &stateStreamMultiContractsTableRowsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type State_StreamMultiContractsTableRowsClient interface {
	Recv() (*TableRowsContractResponse, error)
	grpc.ClientStream
}

type stateStreamMultiContractsTableRowsClient struct {
	grpc.ClientStream
}

func (x *stateStreamMultiContractsTableRowsClient) Recv() (*TableRowsContractResponse, error) {
	m := new(TableRowsContractResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StateServer is the server API for State service.
type StateServer interface {
	// Replaces /v0/state/abi
	GetABI(context.Context, *GetABIRequest) (*GetABIResponse, error)
	// Replaces /v0/state/key_accounts
	GetKeyAccounts(context.Context, *GetKeyAccountsRequest) (*GetKeyAccountsResponse, error)
	// Replaces /v0/state/permission_links
	GetPermissionLinks(context.Context, *GetPermissionLinksRequest) (*GetPermissionLinksResponse, error)
	// Replaces /v0/state/table/row
	GetTableRow(context.Context, *GetTableRowRequest) (*GetTableRowResponse, error)
	// Replaces /v0/state/table
	StreamTableRows(*StreamTableRowsRequest, State_StreamTableRowsServer) error
	// Replaces /v0/state/table_scopes
	StreamTableScopes(*StreamTableScopesRequest, State_StreamTableScopesServer) error
	// Replaces /v0/state/tables/scopes
	StreamMultiScopesTableRows(*StreamMultiScopesTableRowsRequest, State_StreamMultiScopesTableRowsServer) error
	// Replaces /v0/state/tables/accounts
	StreamMultiContractsTableRows(*StreamMultiContractsTableRowsRequest, State_StreamMultiContractsTableRowsServer) error
}

// UnimplementedStateServer can be embedded to have forward compatible implementations.
type UnimplementedStateServer struct {
}

func (*UnimplementedStateServer) GetABI(ctx context.Context, req *GetABIRequest) (*GetABIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetABI not implemented")
}
func (*UnimplementedStateServer) GetKeyAccounts(ctx context.Context, req *GetKeyAccountsRequest) (*GetKeyAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyAccounts not implemented")
}
func (*UnimplementedStateServer) GetPermissionLinks(ctx context.Context, req *GetPermissionLinksRequest) (*GetPermissionLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermissionLinks not implemented")
}
func (*UnimplementedStateServer) GetTableRow(ctx context.Context, req *GetTableRowRequest) (*GetTableRowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableRow not implemented")
}
func (*UnimplementedStateServer) StreamTableRows(req *StreamTableRowsRequest, srv State_StreamTableRowsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTableRows not implemented")
}
func (*UnimplementedStateServer) StreamTableScopes(req *StreamTableScopesRequest, srv State_StreamTableScopesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTableScopes not implemented")
}
func (*UnimplementedStateServer) StreamMultiScopesTableRows(req *StreamMultiScopesTableRowsRequest, srv State_StreamMultiScopesTableRowsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMultiScopesTableRows not implemented")
}
func (*UnimplementedStateServer) StreamMultiContractsTableRows(req *StreamMultiContractsTableRowsRequest, srv State_StreamMultiContractsTableRowsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMultiContractsTableRows not implemented")
}

func RegisterStateServer(s *grpc.Server, srv StateServer) {
	s.RegisterService(&_State_serviceDesc, srv)
}

func _State_GetABI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetABIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetABI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.statedb.v1.State/GetABI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetABI(ctx, req.(*GetABIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetKeyAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetKeyAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.statedb.v1.State/GetKeyAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetKeyAccounts(ctx, req.(*GetKeyAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetPermissionLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetPermissionLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.statedb.v1.State/GetPermissionLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetPermissionLinks(ctx, req.(*GetPermissionLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_GetTableRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).GetTableRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.eosio.statedb.v1.State/GetTableRow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).GetTableRow(ctx, req.(*GetTableRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_StreamTableRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTableRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateServer).StreamTableRows(m, &stateStreamTableRowsServer{stream})
}

type State_StreamTableRowsServer interface {
	Send(*TableRowResponse) error
	grpc.ServerStream
}

type stateStreamTableRowsServer struct {
	grpc.ServerStream
}

func (x *stateStreamTableRowsServer) Send(m *TableRowResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _State_StreamTableScopes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTableScopesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateServer).StreamTableScopes(m, &stateStreamTableScopesServer{stream})
}

type State_StreamTableScopesServer interface {
	Send(*TableScopeResponse) error
	grpc.ServerStream
}

type stateStreamTableScopesServer struct {
	grpc.ServerStream
}

func (x *stateStreamTableScopesServer) Send(m *TableScopeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _State_StreamMultiScopesTableRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMultiScopesTableRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateServer).StreamMultiScopesTableRows(m, &stateStreamMultiScopesTableRowsServer{stream})
}

type State_StreamMultiScopesTableRowsServer interface {
	Send(*TableRowsScopeResponse) error
	grpc.ServerStream
}

type stateStreamMultiScopesTableRowsServer struct {
	grpc.ServerStream
}

func (x *stateStreamMultiScopesTableRowsServer) Send(m *TableRowsScopeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _State_StreamMultiContractsTableRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMultiContractsTableRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateServer).StreamMultiContractsTableRows(m, &stateStreamMultiContractsTableRowsServer{stream})
}

type State_StreamMultiContractsTableRowsServer interface {
	Send(*TableRowsContractResponse) error
	grpc.ServerStream
}

type stateStreamMultiContractsTableRowsServer struct {
	grpc.ServerStream
}

func (x *stateStreamMultiContractsTableRowsServer) Send(m *TableRowsContractResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _State_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.statedb.v1.State",
	HandlerType: (*StateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetABI",
			Handler:    _State_GetABI_Handler,
		},
		{
			MethodName: "GetKeyAccounts",
			Handler:    _State_GetKeyAccounts_Handler,
		},
		{
			MethodName: "GetPermissionLinks",
			Handler:    _State_GetPermissionLinks_Handler,
		},
		{
			MethodName: "GetTableRow",
			Handler:    _State_GetTableRow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTableRows",
			Handler:       _State_StreamTableRows_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTableScopes",
			Handler:       _State_StreamTableScopes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMultiScopesTableRows",
			Handler:       _State_StreamMultiScopesTableRows_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMultiContractsTableRows",
			Handler:       _State_StreamMultiContractsTableRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/eosio/statedb/v1/statedb.proto",
}
