// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/accounthist/v1/accounthist.proto

package pbaccounthist // import "github.com/zhongshuwen/historyexp/pb/dfuse/eosio/accounthist/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1 "github.com/zhongshuwen/historyexp/pb/dfuse/eosio/codec/v1"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetActionsRequest struct {
	Account              uint64   `protobuf:"varint,1,opt,name=account,proto3" json:"account,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor               *Cursor  `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionsRequest) Reset()         { *m = GetActionsRequest{} }
func (m *GetActionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionsRequest) ProtoMessage()    {}
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounthist_4fd7cbe69bb22de5, []int{0}
}
func (m *GetActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsRequest.Unmarshal(m, b)
}
func (m *GetActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsRequest.Merge(dst, src)
}
func (m *GetActionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionsRequest.Size(m)
}
func (m *GetActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsRequest proto.InternalMessageInfo

func (m *GetActionsRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *GetActionsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetActionsRequest) GetCursor() *Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type ActionResponse struct {
	Cursor               *Cursor         `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	ActionTrace          *v1.ActionTrace `protobuf:"bytes,2,opt,name=action_trace,json=actionTrace,proto3" json:"action_trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActionResponse) Reset()         { *m = ActionResponse{} }
func (m *ActionResponse) String() string { return proto.CompactTextString(m) }
func (*ActionResponse) ProtoMessage()    {}
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounthist_4fd7cbe69bb22de5, []int{1}
}
func (m *ActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResponse.Unmarshal(m, b)
}
func (m *ActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResponse.Marshal(b, m, deterministic)
}
func (dst *ActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResponse.Merge(dst, src)
}
func (m *ActionResponse) XXX_Size() int {
	return xxx_messageInfo_ActionResponse.Size(m)
}
func (m *ActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResponse proto.InternalMessageInfo

func (m *ActionResponse) GetCursor() *Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *ActionResponse) GetActionTrace() *v1.ActionTrace {
	if m != nil {
		return m.ActionTrace
	}
	return nil
}

type ActionRow struct {
	Version              uint32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ActionTrace          *v1.ActionTrace `protobuf:"bytes,2,opt,name=action_trace,json=actionTrace,proto3" json:"action_trace,omitempty"`
	LastDeletedSeq       uint64          `protobuf:"varint,3,opt,name=last_deleted_seq,json=lastDeletedSeq,proto3" json:"last_deleted_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActionRow) Reset()         { *m = ActionRow{} }
func (m *ActionRow) String() string { return proto.CompactTextString(m) }
func (*ActionRow) ProtoMessage()    {}
func (*ActionRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounthist_4fd7cbe69bb22de5, []int{2}
}
func (m *ActionRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRow.Unmarshal(m, b)
}
func (m *ActionRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRow.Marshal(b, m, deterministic)
}
func (dst *ActionRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRow.Merge(dst, src)
}
func (m *ActionRow) XXX_Size() int {
	return xxx_messageInfo_ActionRow.Size(m)
}
func (m *ActionRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRow.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRow proto.InternalMessageInfo

func (m *ActionRow) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ActionRow) GetActionTrace() *v1.ActionTrace {
	if m != nil {
		return m.ActionTrace
	}
	return nil
}

func (m *ActionRow) GetLastDeletedSeq() uint64 {
	if m != nil {
		return m.LastDeletedSeq
	}
	return 0
}

type ShardCheckpoint struct {
	InitialStartBlock    uint64   `protobuf:"varint,1,opt,name=initial_start_block,json=initialStartBlock,proto3" json:"initial_start_block,omitempty"`
	TargetStopBlock      uint64   `protobuf:"varint,2,opt,name=target_stop_block,json=targetStopBlock,proto3" json:"target_stop_block,omitempty"`
	LastWrittenBlockNum  uint64   `protobuf:"varint,3,opt,name=last_written_block_num,json=lastWrittenBlockNum,proto3" json:"last_written_block_num,omitempty"`
	LastWrittenBlockId   string   `protobuf:"bytes,4,opt,name=last_written_block_id,json=lastWrittenBlockId,proto3" json:"last_written_block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardCheckpoint) Reset()         { *m = ShardCheckpoint{} }
func (m *ShardCheckpoint) String() string { return proto.CompactTextString(m) }
func (*ShardCheckpoint) ProtoMessage()    {}
func (*ShardCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounthist_4fd7cbe69bb22de5, []int{3}
}
func (m *ShardCheckpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardCheckpoint.Unmarshal(m, b)
}
func (m *ShardCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardCheckpoint.Marshal(b, m, deterministic)
}
func (dst *ShardCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardCheckpoint.Merge(dst, src)
}
func (m *ShardCheckpoint) XXX_Size() int {
	return xxx_messageInfo_ShardCheckpoint.Size(m)
}
func (m *ShardCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_ShardCheckpoint proto.InternalMessageInfo

func (m *ShardCheckpoint) GetInitialStartBlock() uint64 {
	if m != nil {
		return m.InitialStartBlock
	}
	return 0
}

func (m *ShardCheckpoint) GetTargetStopBlock() uint64 {
	if m != nil {
		return m.TargetStopBlock
	}
	return 0
}

func (m *ShardCheckpoint) GetLastWrittenBlockNum() uint64 {
	if m != nil {
		return m.LastWrittenBlockNum
	}
	return 0
}

func (m *ShardCheckpoint) GetLastWrittenBlockId() string {
	if m != nil {
		return m.LastWrittenBlockId
	}
	return ""
}

type ActionRowAppend struct {
	LastDeletedSeq       uint64   `protobuf:"varint,3,opt,name=last_deleted_seq,json=lastDeletedSeq,proto3" json:"last_deleted_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionRowAppend) Reset()         { *m = ActionRowAppend{} }
func (m *ActionRowAppend) String() string { return proto.CompactTextString(m) }
func (*ActionRowAppend) ProtoMessage()    {}
func (*ActionRowAppend) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounthist_4fd7cbe69bb22de5, []int{4}
}
func (m *ActionRowAppend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRowAppend.Unmarshal(m, b)
}
func (m *ActionRowAppend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRowAppend.Marshal(b, m, deterministic)
}
func (dst *ActionRowAppend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRowAppend.Merge(dst, src)
}
func (m *ActionRowAppend) XXX_Size() int {
	return xxx_messageInfo_ActionRowAppend.Size(m)
}
func (m *ActionRowAppend) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRowAppend.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRowAppend proto.InternalMessageInfo

func (m *ActionRowAppend) GetLastDeletedSeq() uint64 {
	if m != nil {
		return m.LastDeletedSeq
	}
	return 0
}

type Cursor struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Magic                uint32   `protobuf:"varint,2,opt,name=magic,proto3" json:"magic,omitempty"`
	Account              uint64   `protobuf:"varint,3,opt,name=account,proto3" json:"account,omitempty"`
	ShardNum             uint32   `protobuf:"varint,4,opt,name=shard_num,json=shardNum,proto3" json:"shard_num,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cursor) Reset()         { *m = Cursor{} }
func (m *Cursor) String() string { return proto.CompactTextString(m) }
func (*Cursor) ProtoMessage()    {}
func (*Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounthist_4fd7cbe69bb22de5, []int{5}
}
func (m *Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cursor.Unmarshal(m, b)
}
func (m *Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cursor.Marshal(b, m, deterministic)
}
func (dst *Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cursor.Merge(dst, src)
}
func (m *Cursor) XXX_Size() int {
	return xxx_messageInfo_Cursor.Size(m)
}
func (m *Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_Cursor proto.InternalMessageInfo

func (m *Cursor) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Cursor) GetMagic() uint32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Cursor) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *Cursor) GetShardNum() uint32 {
	if m != nil {
		return m.ShardNum
	}
	return 0
}

func (m *Cursor) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*GetActionsRequest)(nil), "dfuse.eosio.accounthist.v1.GetActionsRequest")
	proto.RegisterType((*ActionResponse)(nil), "dfuse.eosio.accounthist.v1.ActionResponse")
	proto.RegisterType((*ActionRow)(nil), "dfuse.eosio.accounthist.v1.ActionRow")
	proto.RegisterType((*ShardCheckpoint)(nil), "dfuse.eosio.accounthist.v1.ShardCheckpoint")
	proto.RegisterType((*ActionRowAppend)(nil), "dfuse.eosio.accounthist.v1.ActionRowAppend")
	proto.RegisterType((*Cursor)(nil), "dfuse.eosio.accounthist.v1.Cursor")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountHistoryClient is the client API for AccountHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountHistoryClient interface {
	GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (AccountHistory_GetActionsClient, error)
}

type accountHistoryClient struct {
	cc *grpc.ClientConn
}

func NewAccountHistoryClient(cc *grpc.ClientConn) AccountHistoryClient {
	return &accountHistoryClient{cc}
}

func (c *accountHistoryClient) GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (AccountHistory_GetActionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountHistory_serviceDesc.Streams[0], "/dfuse.eosio.accounthist.v1.AccountHistory/GetActions", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountHistoryGetActionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountHistory_GetActionsClient interface {
	Recv() (*ActionResponse, error)
	grpc.ClientStream
}

type accountHistoryGetActionsClient struct {
	grpc.ClientStream
}

func (x *accountHistoryGetActionsClient) Recv() (*ActionResponse, error) {
	m := new(ActionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AccountHistoryServer is the server API for AccountHistory service.
type AccountHistoryServer interface {
	GetActions(*GetActionsRequest, AccountHistory_GetActionsServer) error
}

func RegisterAccountHistoryServer(s *grpc.Server, srv AccountHistoryServer) {
	s.RegisterService(&_AccountHistory_serviceDesc, srv)
}

func _AccountHistory_GetActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetActionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountHistoryServer).GetActions(m, &accountHistoryGetActionsServer{stream})
}

type AccountHistory_GetActionsServer interface {
	Send(*ActionResponse) error
	grpc.ServerStream
}

type accountHistoryGetActionsServer struct {
	grpc.ServerStream
}

func (x *accountHistoryGetActionsServer) Send(m *ActionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _AccountHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.accounthist.v1.AccountHistory",
	HandlerType: (*AccountHistoryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetActions",
			Handler:       _AccountHistory_GetActions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/eosio/accounthist/v1/accounthist.proto",
}

func init() {
	proto.RegisterFile("dfuse/eosio/accounthist/v1/accounthist.proto", fileDescriptor_accounthist_4fd7cbe69bb22de5)
}

var fileDescriptor_accounthist_4fd7cbe69bb22de5 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0xdb, 0x24, 0xbf, 0x5f, 0x36, 0xb4, 0x21, 0xdb, 0x82, 0xac, 0x70, 0x09, 0xbe, 0x10,
	0x55, 0x60, 0x93, 0xf4, 0x46, 0x4f, 0xfd, 0x23, 0x01, 0x07, 0x8a, 0xe4, 0x20, 0x21, 0x71, 0xb1,
	0xec, 0xf5, 0x10, 0xaf, 0x9a, 0xec, 0x3a, 0xde, 0x71, 0xc2, 0x9f, 0x03, 0xdf, 0x01, 0x09, 0x89,
	0x2f, 0xc6, 0xf7, 0x41, 0xbb, 0xeb, 0x50, 0x07, 0x68, 0xa4, 0x4a, 0xdc, 0x3c, 0xf3, 0xde, 0xbc,
	0x7d, 0x3b, 0x9e, 0x59, 0xf2, 0x38, 0x7d, 0x5f, 0x2a, 0x08, 0x40, 0x2a, 0x2e, 0x83, 0x98, 0x31,
	0x59, 0x0a, 0xcc, 0xb8, 0xc2, 0x60, 0x39, 0xaa, 0x87, 0x7e, 0x5e, 0x48, 0x94, 0xb4, 0x6f, 0xd8,
	0xbe, 0x61, 0xfb, 0x75, 0x78, 0x39, 0xea, 0x0f, 0xea, 0x4a, 0x4c, 0xa6, 0xc0, 0xb4, 0x86, 0xf9,
	0xb0, 0xd5, 0xde, 0x17, 0xd2, 0x7b, 0x0e, 0x78, 0xca, 0x90, 0x4b, 0xa1, 0x42, 0x58, 0x94, 0xa0,
	0x90, 0xba, 0xe4, 0xbf, 0x4a, 0xc8, 0x75, 0x06, 0xce, 0xb0, 0x11, 0xae, 0x43, 0x7a, 0x48, 0x9a,
	0x33, 0x3e, 0xe7, 0xe8, 0xee, 0x0c, 0x9c, 0xe1, 0x5e, 0x68, 0x03, 0xfa, 0x8c, 0xb4, 0x58, 0x59,
	0x28, 0x59, 0xb8, 0xbb, 0x03, 0x67, 0xd8, 0x19, 0x7b, 0xfe, 0xcd, 0x9e, 0xfc, 0x73, 0xc3, 0x0c,
	0xab, 0x0a, 0xef, 0xab, 0x43, 0xf6, 0xed, 0xf1, 0x21, 0xa8, 0x5c, 0x0a, 0x05, 0x35, 0x39, 0xe7,
	0xb6, 0x72, 0xf4, 0x82, 0xdc, 0x89, 0x8d, 0x5a, 0x84, 0x45, 0xcc, 0xc0, 0xf8, 0xec, 0x8c, 0x1f,
	0x6e, 0x28, 0xd8, 0xfb, 0x2f, 0x47, 0xbe, 0x3d, 0xf7, 0x8d, 0x26, 0x86, 0x9d, 0xf8, 0x3a, 0xf0,
	0xbe, 0x39, 0xa4, 0x5d, 0x99, 0x92, 0x2b, 0xdd, 0x8e, 0x25, 0x14, 0x8a, 0x4b, 0x61, 0x0c, 0xed,
	0x85, 0xeb, 0xf0, 0xdf, 0x9c, 0x46, 0x87, 0xe4, 0xee, 0x2c, 0x56, 0x18, 0xa5, 0x30, 0x03, 0x84,
	0x34, 0x52, 0xb0, 0x30, 0x8d, 0x6c, 0x84, 0xfb, 0x3a, 0x7f, 0x61, 0xd3, 0x13, 0x58, 0x78, 0x3f,
	0x1c, 0xd2, 0x9d, 0x64, 0x71, 0x91, 0x9e, 0x67, 0xc0, 0xae, 0x72, 0xc9, 0x05, 0x52, 0x9f, 0x1c,
	0x70, 0xc1, 0x91, 0xc7, 0xb3, 0x48, 0x61, 0x5c, 0x60, 0x94, 0xcc, 0x24, 0xbb, 0xaa, 0x7e, 0x5c,
	0xaf, 0x82, 0x26, 0x1a, 0x39, 0xd3, 0x00, 0x3d, 0x22, 0x3d, 0x8c, 0x8b, 0x29, 0x60, 0xa4, 0x50,
	0xe6, 0x15, 0x7b, 0xc7, 0xb0, 0xbb, 0x16, 0x98, 0xa0, 0xcc, 0x2d, 0xf7, 0x98, 0xdc, 0x37, 0xce,
	0x56, 0x05, 0x47, 0x04, 0x61, 0xc9, 0x91, 0x28, 0xe7, 0x95, 0xbf, 0x03, 0x8d, 0xbe, 0xb5, 0xa0,
	0xa9, 0xb8, 0x2c, 0xe7, 0x74, 0x44, 0xee, 0xfd, 0xa5, 0x88, 0xa7, 0x6e, 0x63, 0xe0, 0x0c, 0xdb,
	0x21, 0xfd, 0xbd, 0xe6, 0x65, 0xea, 0x9d, 0x90, 0xee, 0xaf, 0x76, 0x9f, 0xe6, 0x39, 0x88, 0xf4,
	0x16, 0x4d, 0xf9, 0xee, 0x90, 0x96, 0x9d, 0x82, 0x2d, 0x7f, 0xea, 0x90, 0x34, 0xe7, 0xf1, 0x94,
	0xb3, 0xf5, 0xe0, 0x9a, 0xa0, 0x3e, 0xe8, 0xbb, 0x9b, 0x83, 0xfe, 0x80, 0xb4, 0x95, 0x6e, 0xb4,
	0xb9, 0x6c, 0xc3, 0xd4, 0xfc, 0x6f, 0x12, 0xfa, 0x86, 0x8f, 0x48, 0x57, 0xe9, 0x55, 0x11, 0x0c,
	0x34, 0x9e, 0x40, 0xe1, 0x36, 0xad, 0xb5, 0x75, 0xfa, 0xd2, 0x64, 0xc7, 0x9f, 0xf5, 0x6c, 0x1b,
	0xc1, 0x17, 0x5c, 0xa1, 0x2c, 0x3e, 0x52, 0x4e, 0xc8, 0xf5, 0xbe, 0xd1, 0x27, 0xdb, 0x26, 0xfb,
	0x8f, 0xbd, 0xec, 0x1f, 0x6d, 0xa3, 0x6f, 0x2e, 0xd1, 0x53, 0xe7, 0xec, 0xf5, 0xbb, 0x57, 0x53,
	0x8e, 0x59, 0x99, 0xf8, 0x4c, 0xce, 0x83, 0x4f, 0x99, 0x14, 0x53, 0x95, 0x95, 0x2b, 0x10, 0x41,
	0x66, 0xcd, 0xc0, 0x87, 0x3c, 0xc8, 0x93, 0xe0, 0xe6, 0xd7, 0xe6, 0x24, 0x4f, 0x6a, 0x89, 0xa4,
	0x65, 0x9e, 0x8c, 0xe3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x62, 0x6d, 0x79, 0x1b, 0xa0, 0x04,
	0x00, 0x00,
}
