// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/eosio/accounthist/v1/accounthist.proto

package pbaccounthist

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/zhongshuwen/historyexp/pb/dfuse/eosio/codec/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetActionsRequest struct {
	Account              uint64   `protobuf:"varint,1,opt,name=account,proto3" json:"account,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor               *Cursor  `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionsRequest) Reset()         { *m = GetActionsRequest{} }
func (m *GetActionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionsRequest) ProtoMessage()    {}
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{0}
}

func (m *GetActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsRequest.Unmarshal(m, b)
}
func (m *GetActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsRequest.Marshal(b, m, deterministic)
}
func (m *GetActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsRequest.Merge(m, src)
}
func (m *GetActionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionsRequest.Size(m)
}
func (m *GetActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsRequest proto.InternalMessageInfo

func (m *GetActionsRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *GetActionsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetActionsRequest) GetCursor() *Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type GetTokenActionsRequest struct {
	Account              uint64   `protobuf:"varint,1,opt,name=account,proto3" json:"account,omitempty"`
	Contract             uint64   `protobuf:"varint,2,opt,name=contract,proto3" json:"contract,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor               *Cursor  `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenActionsRequest) Reset()         { *m = GetTokenActionsRequest{} }
func (m *GetTokenActionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenActionsRequest) ProtoMessage()    {}
func (*GetTokenActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{1}
}

func (m *GetTokenActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenActionsRequest.Unmarshal(m, b)
}
func (m *GetTokenActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenActionsRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenActionsRequest.Merge(m, src)
}
func (m *GetTokenActionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenActionsRequest.Size(m)
}
func (m *GetTokenActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenActionsRequest proto.InternalMessageInfo

func (m *GetTokenActionsRequest) GetAccount() uint64 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *GetTokenActionsRequest) GetContract() uint64 {
	if m != nil {
		return m.Contract
	}
	return 0
}

func (m *GetTokenActionsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTokenActionsRequest) GetCursor() *Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type ActionResponse struct {
	Cursor               *Cursor         `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	ActionTrace          *v1.ActionTrace `protobuf:"bytes,2,opt,name=action_trace,json=actionTrace,proto3" json:"action_trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActionResponse) Reset()         { *m = ActionResponse{} }
func (m *ActionResponse) String() string { return proto.CompactTextString(m) }
func (*ActionResponse) ProtoMessage()    {}
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{2}
}

func (m *ActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResponse.Unmarshal(m, b)
}
func (m *ActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResponse.Marshal(b, m, deterministic)
}
func (m *ActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResponse.Merge(m, src)
}
func (m *ActionResponse) XXX_Size() int {
	return xxx_messageInfo_ActionResponse.Size(m)
}
func (m *ActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResponse proto.InternalMessageInfo

func (m *ActionResponse) GetCursor() *Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *ActionResponse) GetActionTrace() *v1.ActionTrace {
	if m != nil {
		return m.ActionTrace
	}
	return nil
}

type ActionRow struct {
	Version              uint32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ActionTrace          *v1.ActionTrace `protobuf:"bytes,2,opt,name=action_trace,json=actionTrace,proto3" json:"action_trace,omitempty"`
	LastDeletedSeq       uint64          `protobuf:"varint,3,opt,name=last_deleted_seq,json=lastDeletedSeq,proto3" json:"last_deleted_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActionRow) Reset()         { *m = ActionRow{} }
func (m *ActionRow) String() string { return proto.CompactTextString(m) }
func (*ActionRow) ProtoMessage()    {}
func (*ActionRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{3}
}

func (m *ActionRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRow.Unmarshal(m, b)
}
func (m *ActionRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRow.Marshal(b, m, deterministic)
}
func (m *ActionRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRow.Merge(m, src)
}
func (m *ActionRow) XXX_Size() int {
	return xxx_messageInfo_ActionRow.Size(m)
}
func (m *ActionRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRow.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRow proto.InternalMessageInfo

func (m *ActionRow) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ActionRow) GetActionTrace() *v1.ActionTrace {
	if m != nil {
		return m.ActionTrace
	}
	return nil
}

func (m *ActionRow) GetLastDeletedSeq() uint64 {
	if m != nil {
		return m.LastDeletedSeq
	}
	return 0
}

type ShardCheckpoint struct {
	InitialStartBlock    uint64   `protobuf:"varint,1,opt,name=initial_start_block,json=initialStartBlock,proto3" json:"initial_start_block,omitempty"`
	TargetStopBlock      uint64   `protobuf:"varint,2,opt,name=target_stop_block,json=targetStopBlock,proto3" json:"target_stop_block,omitempty"`
	LastWrittenBlockNum  uint64   `protobuf:"varint,3,opt,name=last_written_block_num,json=lastWrittenBlockNum,proto3" json:"last_written_block_num,omitempty"`
	LastWrittenBlockId   string   `protobuf:"bytes,4,opt,name=last_written_block_id,json=lastWrittenBlockId,proto3" json:"last_written_block_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardCheckpoint) Reset()         { *m = ShardCheckpoint{} }
func (m *ShardCheckpoint) String() string { return proto.CompactTextString(m) }
func (*ShardCheckpoint) ProtoMessage()    {}
func (*ShardCheckpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{4}
}

func (m *ShardCheckpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardCheckpoint.Unmarshal(m, b)
}
func (m *ShardCheckpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardCheckpoint.Marshal(b, m, deterministic)
}
func (m *ShardCheckpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardCheckpoint.Merge(m, src)
}
func (m *ShardCheckpoint) XXX_Size() int {
	return xxx_messageInfo_ShardCheckpoint.Size(m)
}
func (m *ShardCheckpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardCheckpoint.DiscardUnknown(m)
}

var xxx_messageInfo_ShardCheckpoint proto.InternalMessageInfo

func (m *ShardCheckpoint) GetInitialStartBlock() uint64 {
	if m != nil {
		return m.InitialStartBlock
	}
	return 0
}

func (m *ShardCheckpoint) GetTargetStopBlock() uint64 {
	if m != nil {
		return m.TargetStopBlock
	}
	return 0
}

func (m *ShardCheckpoint) GetLastWrittenBlockNum() uint64 {
	if m != nil {
		return m.LastWrittenBlockNum
	}
	return 0
}

func (m *ShardCheckpoint) GetLastWrittenBlockId() string {
	if m != nil {
		return m.LastWrittenBlockId
	}
	return ""
}

type ActionRowAppend struct {
	LastDeletedSeq       uint64   `protobuf:"varint,3,opt,name=last_deleted_seq,json=lastDeletedSeq,proto3" json:"last_deleted_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionRowAppend) Reset()         { *m = ActionRowAppend{} }
func (m *ActionRowAppend) String() string { return proto.CompactTextString(m) }
func (*ActionRowAppend) ProtoMessage()    {}
func (*ActionRowAppend) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{5}
}

func (m *ActionRowAppend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRowAppend.Unmarshal(m, b)
}
func (m *ActionRowAppend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRowAppend.Marshal(b, m, deterministic)
}
func (m *ActionRowAppend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRowAppend.Merge(m, src)
}
func (m *ActionRowAppend) XXX_Size() int {
	return xxx_messageInfo_ActionRowAppend.Size(m)
}
func (m *ActionRowAppend) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRowAppend.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRowAppend proto.InternalMessageInfo

func (m *ActionRowAppend) GetLastDeletedSeq() uint64 {
	if m != nil {
		return m.LastDeletedSeq
	}
	return 0
}

type Cursor struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Magic                uint32   `protobuf:"varint,2,opt,name=magic,proto3" json:"magic,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ShardNum             uint32   `protobuf:"varint,5,opt,name=shard_num,json=shardNum,proto3" json:"shard_num,omitempty"`
	SequenceNumber       uint64   `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cursor) Reset()         { *m = Cursor{} }
func (m *Cursor) String() string { return proto.CompactTextString(m) }
func (*Cursor) ProtoMessage()    {}
func (*Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c22ddb60199ece6, []int{6}
}

func (m *Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cursor.Unmarshal(m, b)
}
func (m *Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cursor.Marshal(b, m, deterministic)
}
func (m *Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cursor.Merge(m, src)
}
func (m *Cursor) XXX_Size() int {
	return xxx_messageInfo_Cursor.Size(m)
}
func (m *Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_Cursor proto.InternalMessageInfo

func (m *Cursor) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Cursor) GetMagic() uint32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Cursor) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Cursor) GetShardNum() uint32 {
	if m != nil {
		return m.ShardNum
	}
	return 0
}

func (m *Cursor) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*GetActionsRequest)(nil), "dfuse.eosio.accounthist.v1.GetActionsRequest")
	proto.RegisterType((*GetTokenActionsRequest)(nil), "dfuse.eosio.accounthist.v1.GetTokenActionsRequest")
	proto.RegisterType((*ActionResponse)(nil), "dfuse.eosio.accounthist.v1.ActionResponse")
	proto.RegisterType((*ActionRow)(nil), "dfuse.eosio.accounthist.v1.ActionRow")
	proto.RegisterType((*ShardCheckpoint)(nil), "dfuse.eosio.accounthist.v1.ShardCheckpoint")
	proto.RegisterType((*ActionRowAppend)(nil), "dfuse.eosio.accounthist.v1.ActionRowAppend")
	proto.RegisterType((*Cursor)(nil), "dfuse.eosio.accounthist.v1.Cursor")
}

func init() {
	proto.RegisterFile("dfuse/eosio/accounthist/v1/accounthist.proto", fileDescriptor_4c22ddb60199ece6)
}

var fileDescriptor_4c22ddb60199ece6 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0xc7, 0xe5, 0x67, 0x5d, 0x9f, 0xed, 0xec, 0xa5, 0x9b, 0x37, 0xa6, 0x52, 0x6e, 0x4a, 0x6f,
	0xa8, 0x26, 0x48, 0x68, 0x77, 0xc7, 0xae, 0xf6, 0x22, 0x0d, 0x2e, 0x18, 0x52, 0x3a, 0x09, 0x89,
	0x9b, 0x28, 0x75, 0x0e, 0x8d, 0xd5, 0xd6, 0xce, 0x62, 0xa7, 0x63, 0x20, 0xc4, 0x57, 0x40, 0x48,
	0x88, 0x5b, 0xbe, 0x14, 0xdf, 0x07, 0xd9, 0x4e, 0xb6, 0x0e, 0xb6, 0x42, 0x25, 0xee, 0x72, 0xde,
	0xfe, 0xf9, 0xf9, 0xf8, 0xf8, 0xc0, 0xe3, 0xf8, 0x6d, 0xae, 0xd0, 0x47, 0xa9, 0xb8, 0xf4, 0x23,
	0xc6, 0x64, 0x2e, 0x74, 0xc2, 0x95, 0xf6, 0x27, 0x9d, 0x69, 0xd3, 0x4b, 0x33, 0xa9, 0x25, 0x6d,
	0xd8, 0x6c, 0xcf, 0x66, 0x7b, 0xd3, 0xe1, 0x49, 0xa7, 0xd1, 0x9c, 0x56, 0x62, 0x32, 0x46, 0x66,
	0x34, 0xec, 0x87, 0xab, 0x6e, 0x7d, 0x82, 0xcd, 0x13, 0xd4, 0x07, 0x4c, 0x73, 0x29, 0x54, 0x80,
	0xe7, 0x39, 0x2a, 0x4d, 0xeb, 0xf0, 0x7f, 0x21, 0x54, 0x27, 0x4d, 0xd2, 0xae, 0x04, 0xa5, 0x49,
	0xb7, 0x61, 0x71, 0xc4, 0xc7, 0x5c, 0xd7, 0xff, 0x6b, 0x92, 0xf6, 0x5a, 0xe0, 0x0c, 0xfa, 0x0c,
	0xaa, 0x2c, 0xcf, 0x94, 0xcc, 0xea, 0x0b, 0x4d, 0xd2, 0x5e, 0xe9, 0xb6, 0xbc, 0xbb, 0x99, 0xbc,
	0x23, 0x9b, 0x19, 0x14, 0x15, 0xad, 0xef, 0x04, 0x76, 0x4e, 0x50, 0x9f, 0xc9, 0x21, 0x8a, 0xbf,
	0xc6, 0x68, 0xc0, 0x12, 0x93, 0x42, 0x67, 0x11, 0x73, 0x24, 0x95, 0xe0, 0xca, 0xbe, 0x46, 0x5c,
	0xb8, 0x1d, 0xb1, 0x32, 0x37, 0xe2, 0x17, 0x02, 0xeb, 0x0e, 0x2d, 0x40, 0x95, 0x4a, 0xa1, 0x70,
	0x4a, 0x8e, 0xcc, 0x2b, 0x47, 0x8f, 0x61, 0x35, 0xb2, 0x6a, 0xa1, 0x01, 0x46, 0x7b, 0x80, 0x95,
	0xee, 0xc3, 0x1b, 0x0a, 0xee, 0x8a, 0x26, 0x1d, 0xcf, 0xfd, 0xf7, 0xcc, 0x24, 0x06, 0x2b, 0xd1,
	0xb5, 0xd1, 0xfa, 0x4a, 0x60, 0xb9, 0x80, 0x92, 0x17, 0xa6, 0x55, 0x13, 0xcc, 0x14, 0x97, 0xc2,
	0x02, 0xad, 0x05, 0xa5, 0xf9, 0x6f, 0xfe, 0x46, 0xdb, 0xb0, 0x31, 0x8a, 0x94, 0x0e, 0x63, 0x1c,
	0xa1, 0xc6, 0x38, 0x54, 0x78, 0x6e, 0xfb, 0x5b, 0x09, 0xd6, 0x8d, 0xff, 0xd8, 0xb9, 0x7b, 0x78,
	0xde, 0xfa, 0x41, 0xa0, 0xd6, 0x4b, 0xa2, 0x2c, 0x3e, 0x4a, 0x90, 0x0d, 0x53, 0xc9, 0x85, 0xa6,
	0x1e, 0x6c, 0x71, 0xc1, 0x35, 0x8f, 0x46, 0xa1, 0xd2, 0x51, 0xa6, 0xc3, 0xfe, 0x48, 0xb2, 0x61,
	0x71, 0xa9, 0x9b, 0x45, 0xa8, 0x67, 0x22, 0x87, 0x26, 0x40, 0x77, 0x61, 0x53, 0x47, 0xd9, 0x00,
	0x75, 0xa8, 0xb4, 0x4c, 0x8b, 0x6c, 0x77, 0xcf, 0x35, 0x17, 0xe8, 0x69, 0x99, 0xba, 0xdc, 0x3d,
	0xd8, 0xb1, 0x64, 0x17, 0x19, 0xd7, 0x1a, 0x85, 0x4b, 0x0e, 0x45, 0x3e, 0x2e, 0xf8, 0xb6, 0x4c,
	0xf4, 0xb5, 0x0b, 0xda, 0x8a, 0xd3, 0x7c, 0x4c, 0x3b, 0x70, 0xef, 0x96, 0x22, 0x1e, 0xdb, 0xe1,
	0x58, 0x0e, 0xe8, 0xaf, 0x35, 0x2f, 0xe2, 0xd6, 0x3e, 0xd4, 0xae, 0xda, 0x7d, 0x90, 0xa6, 0x28,
	0xe2, 0x39, 0x9a, 0xf2, 0x99, 0x40, 0xd5, 0x4d, 0xc1, 0x8c, 0x9b, 0xda, 0x86, 0xc5, 0x71, 0x34,
	0xe0, 0xac, 0x7c, 0x5b, 0xd6, 0xa0, 0x1b, 0xb0, 0x30, 0xc4, 0x4b, 0xab, 0xbb, 0x1a, 0x98, 0x4f,
	0xfa, 0x00, 0x96, 0x95, 0x69, 0xb0, 0x3d, 0xe4, 0xa2, 0xcd, 0x5d, 0xb2, 0x0e, 0x73, 0xb2, 0x47,
	0x50, 0x53, 0xe6, 0xf9, 0x08, 0x86, 0x26, 0xde, 0xc7, 0xac, 0x5e, 0x75, 0x48, 0xa5, 0xfb, 0xd4,
	0x7a, 0xbb, 0x1f, 0xcc, 0x4c, 0xdb, 0x31, 0x7d, 0xce, 0x95, 0x96, 0xd9, 0x25, 0xe5, 0x00, 0xd7,
	0xab, 0x80, 0x3e, 0x99, 0x35, 0xd1, 0xbf, 0xad, 0x8c, 0xc6, 0xee, 0xac, 0xf4, 0x9b, 0x8f, 0xe7,
	0x29, 0xe9, 0x7e, 0x23, 0xb0, 0x53, 0xfc, 0xfd, 0xa8, 0x78, 0xb7, 0x25, 0xc5, 0x47, 0xb8, 0x6f,
	0xd5, 0x6f, 0x04, 0x4b, 0xa8, 0xee, 0x1f, 0xa0, 0x6e, 0xd9, 0x22, 0xf3, 0x91, 0x1d, 0xbe, 0x7a,
	0xf3, 0x72, 0xc0, 0x75, 0x92, 0xf7, 0x3d, 0x26, 0xc7, 0xfe, 0xfb, 0x44, 0x8a, 0x81, 0x4a, 0xf2,
	0x0b, 0x14, 0x7e, 0xe2, 0x00, 0xf1, 0x5d, 0xea, 0xa7, 0x7d, 0xff, 0xee, 0x15, 0xbd, 0x9f, 0xf6,
	0xa7, 0x1c, 0xfd, 0xaa, 0xdd, 0xb3, 0x7b, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x8e, 0x74,
	0x3e, 0xd5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountHistoryClient is the client API for AccountHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountHistoryClient interface {
	GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (AccountHistory_GetActionsClient, error)
}

type accountHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountHistoryClient(cc grpc.ClientConnInterface) AccountHistoryClient {
	return &accountHistoryClient{cc}
}

func (c *accountHistoryClient) GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (AccountHistory_GetActionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountHistory_serviceDesc.Streams[0], "/dfuse.eosio.accounthist.v1.AccountHistory/GetActions", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountHistoryGetActionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountHistory_GetActionsClient interface {
	Recv() (*ActionResponse, error)
	grpc.ClientStream
}

type accountHistoryGetActionsClient struct {
	grpc.ClientStream
}

func (x *accountHistoryGetActionsClient) Recv() (*ActionResponse, error) {
	m := new(ActionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AccountHistoryServer is the server API for AccountHistory service.
type AccountHistoryServer interface {
	GetActions(*GetActionsRequest, AccountHistory_GetActionsServer) error
}

// UnimplementedAccountHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedAccountHistoryServer struct {
}

func (*UnimplementedAccountHistoryServer) GetActions(req *GetActionsRequest, srv AccountHistory_GetActionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetActions not implemented")
}

func RegisterAccountHistoryServer(s *grpc.Server, srv AccountHistoryServer) {
	s.RegisterService(&_AccountHistory_serviceDesc, srv)
}

func _AccountHistory_GetActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetActionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountHistoryServer).GetActions(m, &accountHistoryGetActionsServer{stream})
}

type AccountHistory_GetActionsServer interface {
	Send(*ActionResponse) error
	grpc.ServerStream
}

type accountHistoryGetActionsServer struct {
	grpc.ServerStream
}

func (x *accountHistoryGetActionsServer) Send(m *ActionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _AccountHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.accounthist.v1.AccountHistory",
	HandlerType: (*AccountHistoryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetActions",
			Handler:       _AccountHistory_GetActions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/eosio/accounthist/v1/accounthist.proto",
}

// AccountContractHistoryClient is the client API for AccountContractHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountContractHistoryClient interface {
	GetAccountContractActions(ctx context.Context, in *GetTokenActionsRequest, opts ...grpc.CallOption) (AccountContractHistory_GetAccountContractActionsClient, error)
}

type accountContractHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountContractHistoryClient(cc grpc.ClientConnInterface) AccountContractHistoryClient {
	return &accountContractHistoryClient{cc}
}

func (c *accountContractHistoryClient) GetAccountContractActions(ctx context.Context, in *GetTokenActionsRequest, opts ...grpc.CallOption) (AccountContractHistory_GetAccountContractActionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountContractHistory_serviceDesc.Streams[0], "/dfuse.eosio.accounthist.v1.AccountContractHistory/GetAccountContractActions", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountContractHistoryGetAccountContractActionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountContractHistory_GetAccountContractActionsClient interface {
	Recv() (*ActionResponse, error)
	grpc.ClientStream
}

type accountContractHistoryGetAccountContractActionsClient struct {
	grpc.ClientStream
}

func (x *accountContractHistoryGetAccountContractActionsClient) Recv() (*ActionResponse, error) {
	m := new(ActionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AccountContractHistoryServer is the server API for AccountContractHistory service.
type AccountContractHistoryServer interface {
	GetAccountContractActions(*GetTokenActionsRequest, AccountContractHistory_GetAccountContractActionsServer) error
}

// UnimplementedAccountContractHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedAccountContractHistoryServer struct {
}

func (*UnimplementedAccountContractHistoryServer) GetAccountContractActions(req *GetTokenActionsRequest, srv AccountContractHistory_GetAccountContractActionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAccountContractActions not implemented")
}

func RegisterAccountContractHistoryServer(s *grpc.Server, srv AccountContractHistoryServer) {
	s.RegisterService(&_AccountContractHistory_serviceDesc, srv)
}

func _AccountContractHistory_GetAccountContractActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTokenActionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountContractHistoryServer).GetAccountContractActions(m, &accountContractHistoryGetAccountContractActionsServer{stream})
}

type AccountContractHistory_GetAccountContractActionsServer interface {
	Send(*ActionResponse) error
	grpc.ServerStream
}

type accountContractHistoryGetAccountContractActionsServer struct {
	grpc.ServerStream
}

func (x *accountContractHistoryGetAccountContractActionsServer) Send(m *ActionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _AccountContractHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.eosio.accounthist.v1.AccountContractHistory",
	HandlerType: (*AccountContractHistoryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAccountContractActions",
			Handler:       _AccountContractHistory_GetAccountContractActions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfuse/eosio/accounthist/v1/accounthist.proto",
}
